import React from 'react';
import { Drawer, DrawerContent, DrawerHeader, DrawerTitle, DrawerClose } from '@/components/ui/drawer';
import { X, Shield, Lock, Bot, AlertTriangle, FileText, Mail } from 'lucide-react';

interface AboutSheetProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

const Divider = () => <div className="my-4" style={{ height: 1, background: '#F0F4F8' }} />;

const SectionHeader = ({ icon: Icon, label }: { icon: React.ElementType; label: string }) => (
  <div className="flex items-center gap-1.5 mb-2">
    <Icon size={14} style={{ color: '#6B7C93' }} />
    <h4 className="text-[12px] font-bold uppercase tracking-wider" style={{ color: '#6B7C93' }}>{label}</h4>
  </div>
);

const InfoRow = ({ label, value }: { label: string; value: React.ReactNode }) => (
  <div className="flex justify-between py-1">
    <span className="text-[13px]" style={{ color: '#6B7C93' }}>{label}</span>
    <span className="text-[13px] font-bold" style={{ color: '#1A2332' }}>{value}</span>
  </div>
);

const BodyText = ({ children }: { children: React.ReactNode }) => (
  <p className="text-[13px] leading-[20px]" style={{ color: '#475569' }}>{children}</p>
);

const AboutSheet = ({ open, onOpenChange }: AboutSheetProps) => {
  return (
    <Drawer open={open} onOpenChange={onOpenChange}>
      <DrawerContent className="max-h-[90vh]">
        <DrawerHeader className="flex items-center justify-between px-5 pb-2">
          <DrawerTitle className="text-[17px] font-bold" style={{ color: '#1A2332' }}>About PediLog</DrawerTitle>
          <DrawerClose asChild>
            <button className="p-1.5 rounded-full hover:bg-muted"><X size={20} style={{ color: '#6B7C93' }} /></button>
          </DrawerClose>
        </DrawerHeader>

        <div className="px-5 pb-8 overflow-y-auto">
          {/* Logo */}
          <div className="flex items-center gap-3 mb-4">
            <div className="w-12 h-12 bg-primary rounded-xl flex items-center justify-center shadow-brand">
              <span className="text-primary-foreground font-bold text-xl">P</span>
            </div>
            <div>
              <div className="text-[16px] font-bold" style={{ color: '#1A2332' }}>PediLog</div>
              <div className="text-[12px]" style={{ color: '#6B7C93' }}>Medical Logbook</div>
            </div>
          </div>

          <Divider />

          {/* App Info */}
          <SectionHeader icon={FileText} label="App Info" />
          <InfoRow label="App Version" value="2.1.0" />
          <InfoRow label="Schema Version" value="3" />
          <InfoRow label="Encryption" value={<span className="flex items-center gap-1"><Shield size={12} /> AES-256</span>} />
          <InfoRow label="Platform" value="iOS / Android" />

          <Divider />

          {/* Privacy */}
          <SectionHeader icon={Lock} label="Privacy & Data Security" />
          <BodyText>
            All patient data is stored locally on your device using AES-256 encryption. No data is transmitted to any server without your explicit action.
          </BodyText>
          <div className="h-3" />
          <BodyText>
            Google Drive sync, if enabled, uses encrypted backups. Your Google credentials are never stored by PediLog.
          </BodyText>

          <Divider />

          {/* AI */}
          <SectionHeader icon={Bot} label="AI & Data Usage" />
          <BodyText>
            AI features (Insights, CasePearl, GroupPearl) send de-identified data only to the AI provider. Patient names and file numbers are never included in AI requests.
          </BodyText>
          <div className="h-3" />
          <BodyText>
            AI responses are generated by Anthropic Claude and are for educational and reference purposes only.
          </BodyText>

          <Divider />

          {/* Disclaimer */}
          <SectionHeader icon={AlertTriangle} label="Medical Disclaimer" />
          <BodyText>
            PediLog is a personal medical logbook tool intended for use by qualified healthcare professionals only.
          </BodyText>
          <div className="h-3" />
          <BodyText>
            AI-generated content does not constitute medical advice and should not replace clinical judgment. The developer assumes no liability for clinical decisions made based on AI-generated outputs.
          </BodyText>

          <Divider />

          {/* Terms */}
          <SectionHeader icon={FileText} label="Terms & Conditions" />
          <BodyText>By using PediLog, you agree that:</BodyText>
          <ul className="mt-2 space-y-1.5 pl-1">
            {[
              'You are a licensed healthcare professional',
              'You are responsible for the accuracy of entered data',
              'You will comply with local patient data protection laws (HIPAA, GDPR, or equivalent)',
              'The developer is not liable for data loss or breach resulting from device compromise',
            ].map((item, i) => (
              <li key={i} className="flex items-start gap-2 text-[13px] leading-[20px]" style={{ color: '#475569' }}>
                <span className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: '#94A3B8' }} />
                {item}
              </li>
            ))}
          </ul>

          <Divider />

          {/* Contact */}
          <SectionHeader icon={Mail} label="Contact & Support" />
          <BodyText>
            For support or inquiries:{' '}
            <a href="mailto:support@pedilog.app" className="font-bold" style={{ color: '#2563EB' }}>support@pedilog.app</a>
          </BodyText>
        </div>
      </DrawerContent>
    </Drawer>
  );
};

export default AboutSheet;
